model_save_path: ./data/models/best_xgboost_model.pkl
nn_model:
  batch_size: 32
  dropout: 0.2
  hidden_dim: 128
  input_dim: 70
  learning_rate: 0.001
  num_epochs: 100
  num_layers: 3
  patience: 20
nn_model_inference:
  dropout: 0.20099562033114954
  hidden_dim: 512
  input_dim: 70
  num_layers: 5
nn_model_path: ./data/models/best_nn_model.pt
optuna_trials: 50
random_state: 42
raw_data_path: ./data/raw/MLE-Assignment.csv
x_test_path: ./data/processed/x_test.csv
x_train_path: ./data/processed/x_train.csv
y_test_path: ./data/processed/y_test.csv
y_train_path: ./data/processed/y_train.csv
